name: webitel ui-chats pkg publish

on:
  #  https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:
    inputs:
      npm_tag:
        description: "NPM tag - latest, next, etc."
        required: false
        default: latest
        type: string

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          registry-url: https://registry.npmjs.org

      - name: Publish release
        id: publish_release
        env:
          HUSKY: 0 #https://typicode.github.io/husky/how-to.html#ci-server-and-docker
          NPM_TAG: ${{ inputs.npm_tag }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}    
          cd packages/ui-chats
          npm ci
          npm run make-all

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
